Repository KOSA-COTW/backend, pull requests merged in 2025-08, with the labels that each got.

#11 Feat/login signup pjs
  build.gradle
  docker-compose.yml
  src/main/java/cotw/server/common/jwt/CustomLogoutFilter.java
  src/main/java/cotw/server/common/jwt/CustomUserDetails.java
  src/main/java/cotw/server/common/jwt/CustomUserDetailsService.java
  src/main/java/cotw/server/common/jwt/JwtFilter.java
  src/main/java/cotw/server/common/jwt/JwtUtil.java
  src/main/java/cotw/server/common/jwt/LoginFilter.java
  src/main/java/cotw/server/common/jwt/entity/RefreshToken.java
  src/main/java/cotw/server/common/jwt/repository/RefreshTokenRepository.java
  src/main/java/cotw/server/common/security/CorsMvcConfig.java
  src/main/java/cotw/server/common/security/SecurityConfig.java
  src/main/java/cotw/server/domain/member/Dto/request/LoginRequestDTO.java
  src/main/java/cotw/server/domain/member/Dto/request/SignUpRequestDTO.java
  src/main/java/cotw/server/domain/member/Dto/response/SignUpResponseDTO.java
  src/main/java/cotw/server/domain/member/controller/MemberController.java
  src/main/java/cotw/server/domain/member/controller/ReissueController.java
  src/main/java/cotw/server/domain/member/entity/Member.java
  src/main/java/cotw/server/domain/member/repository/MemberRepository.java
Labels: feat

#12 feat: 게시글 공개 여부 필드 및 권한 변경 기능 추가
  src/main/java/cotw/server/common/jwt/CustomUserDetails.java
  src/main/java/cotw/server/common/jwt/JwtFilter.java
  src/main/java/cotw/server/common/jwt/LoginFilter.java
  src/main/java/cotw/server/domain/board/controller/PostController.java
  src/main/java/cotw/server/domain/board/domain/Category.java
  src/main/java/cotw/server/domain/board/domain/Image.java
  src/main/java/cotw/server/domain/board/domain/Post.java
  src/main/java/cotw/server/domain/board/dto/request/PostCreateRequestDto.java
  src/main/java/cotw/server/domain/board/dto/request/PostUpdateRequestDto.java
  src/main/java/cotw/server/domain/board/dto/response/PostResponseDto.java
  src/main/java/cotw/server/domain/board/entity/Category.java
  src/main/java/cotw/server/domain/board/entity/Comment.java
  src/main/java/cotw/server/domain/board/entity/Image.java
  src/main/java/cotw/server/domain/board/entity/Participant.java
  src/main/java/cotw/server/domain/board/entity/Post.java
  src/main/java/cotw/server/domain/board/repository/PostRepository.java
  src/main/java/cotw/server/domain/board/service/PostService.java
Labels: feat

#15 feat: 메인페이지에 마감 임박 공개 기부글 6개만 노출되도록 수정
  src/main/java/cotw/server/domain/board/controller/PostController.java
  src/main/java/cotw/server/domain/board/repository/PostRepository.java
  src/main/java/cotw/server/domain/board/service/PostService.java
Labels: feat

#17 Feat/comment
  src/main/java/cotw/server/common/BaseEntity.java
  src/main/java/cotw/server/common/jwt/CustomUserDetails.java
  src/main/java/cotw/server/common/jwt/JwtFilter.java
  src/main/java/cotw/server/common/jwt/LoginFilter.java
  src/main/java/cotw/server/common/security/SecurityConfig.java
  src/main/java/cotw/server/domain/board/entity/Comment.java
  src/main/java/cotw/server/domain/comment/controller/CommentAdminController.java
  src/main/java/cotw/server/domain/comment/controller/CommentController.java
  src/main/java/cotw/server/domain/comment/controller/CommentLikeController.java
  src/main/java/cotw/server/domain/comment/controller/CommentReportController.java
  src/main/java/cotw/server/domain/comment/dto/request/CreateCommentRequest.java
  src/main/java/cotw/server/domain/comment/dto/request/LikeRequest.java
  src/main/java/cotw/server/domain/comment/dto/request/ReportRequest.java
  src/main/java/cotw/server/domain/comment/dto/request/UpdateCommentRequest.java
  src/main/java/cotw/server/domain/comment/dto/response/CommentResponse.java
  src/main/java/cotw/server/domain/comment/dto/response/LikeResponse.java
  src/main/java/cotw/server/domain/comment/dto/response/ReportResponse.java
  src/main/java/cotw/server/domain/comment/entity/CommentLike.java
  src/main/java/cotw/server/domain/comment/entity/CommentReport.java
  src/main/java/cotw/server/domain/comment/entity/ReportReason.java
  src/main/java/cotw/server/domain/comment/repository/CommentLikeRepository.java
  src/main/java/cotw/server/domain/comment/repository/CommentReportRepository.java
  src/main/java/cotw/server/domain/comment/repository/CommentRepository.java
  src/main/java/cotw/server/domain/comment/service/CommentLikeService.java
  src/main/java/cotw/server/domain/comment/service/CommentReportService.java
  src/main/java/cotw/server/domain/comment/service/CommentService.java
  src/main/resources/application.yml
Labels: feat

#19 Feat/payment
  .claude/settings.local.json
  build.gradle
  src/main/java/cotw/server/common/jwt/CustomUserDetails.java
  src/main/java/cotw/server/common/jwt/JwtFilter.java
  src/main/java/cotw/server/common/jwt/JwtUtil.java
  src/main/java/cotw/server/common/jwt/LoginFilter.java
  src/main/java/cotw/server/common/jwt/entity/RefreshToken.java
  src/main/java/cotw/server/common/security/SecurityConfig.java
  src/main/java/cotw/server/domain/board/entity/Post.java
  src/main/java/cotw/server/domain/member/Dto/request/SignUpRequestDTO.java
  src/main/java/cotw/server/domain/member/Dto/response/SignUpResponseDTO.java
  src/main/java/cotw/server/domain/member/controller/ReissueController.java
  src/main/java/cotw/server/domain/member/entity/Member.java
  src/main/java/cotw/server/domain/payment/config/AsyncConfig.java
  src/main/java/cotw/server/domain/payment/config/OrderIdGenerator.java
  src/main/java/cotw/server/domain/payment/config/RestClientConfig.java
  src/main/java/cotw/server/domain/payment/config/SecurityUtil.java
  src/main/java/cotw/server/domain/payment/config/TossPaymentConfig.java
  src/main/java/cotw/server/domain/payment/controller/PaymentController.java
  src/main/java/cotw/server/domain/payment/dto/request/PaymentConfirmRequest.java
  src/main/java/cotw/server/domain/payment/dto/request/PaymentCreateRequest.java
  src/main/java/cotw/server/domain/payment/dto/response/PaymentConfirmResponse.java
  src/main/java/cotw/server/domain/payment/dto/response/PaymentCreateResponse.java
  src/main/java/cotw/server/domain/payment/dto/response/PaymentDetailResponse.java
  src/main/java/cotw/server/domain/payment/dto/response/TossPaymentResponse.java
  src/main/java/cotw/server/domain/payment/entity/PaymentEvent.java
  src/main/java/cotw/server/domain/payment/entity/PaymentLedger.java
  src/main/java/cotw/server/domain/payment/entity/PaymentOrder.java
  src/main/java/cotw/server/domain/payment/entity/PaymentStatus.java
  src/main/java/cotw/server/domain/payment/entity/PaymentType.java
  src/main/java/cotw/server/domain/payment/exception/PaymentException.java
  src/main/java/cotw/server/domain/payment/exception/PaymentExceptionHandler.java
  src/main/java/cotw/server/domain/payment/repository/PaymentLedgerRepository.java
  src/main/java/cotw/server/domain/payment/repository/PaymentOrderRepository.java
  src/main/java/cotw/server/domain/payment/repository/PaymentRepository.java
  src/main/java/cotw/server/domain/payment/service/LedgerService.java
  src/main/java/cotw/server/domain/payment/service/PaymentService.java
  src/main/resources/application-core.yml
  src/test/java/cotw/server/domain/payment/PaymentDataIntegrityTest.java
  src/test/java/cotw/server/domain/payment/PaymentIntegrationTest.java
  src/test/java/cotw/server/domain/payment/config/TestConfig.java
  src/test/java/cotw/server/domain/payment/controller/PaymentControllerTest.java
  src/test/java/cotw/server/domain/payment/entity/PaymentEventTest.java
  src/test/java/cotw/server/domain/payment/entity/PaymentLedgerTest.java
  src/test/java/cotw/server/domain/payment/service/LedgerServiceTest.java
  src/test/java/cotw/server/domain/payment/service/PaymentServiceTest.java
  src/test/resources/application-test.yml
Labels: feat

#21 fix: 게시글 생성 권한을 로그인 사용자 전체로 수정
  src/main/java/cotw/server/common/security/SecurityConfig.java
  src/main/java/cotw/server/domain/board/controller/PostController.java
  src/main/java/cotw/server/domain/board/dto/response/PostListResponseDto.java
  src/main/java/cotw/server/domain/board/dto/response/PostResponseDto.java
  src/main/java/cotw/server/domain/board/entity/Post.java
Labels: fix

#25 refactor: 전체적인 코드, 테스트 수정
  src/main/java/cotw/server/domain/payment/config/OrderIdGenerator.java
  src/main/java/cotw/server/domain/payment/config/TossPaymentConfig.java
  src/main/java/cotw/server/domain/payment/controller/PaymentController.java
  src/main/java/cotw/server/domain/payment/dto/response/PaymentConfirmResponse.java
  src/main/java/cotw/server/domain/payment/exception/PaymentException.java
  src/main/java/cotw/server/domain/payment/exception/PaymentIdempotencyException.java
  src/main/java/cotw/server/domain/payment/repository/PaymentLedgerRepository.java
  src/main/java/cotw/server/domain/payment/repository/PaymentOrderRepository.java
  src/main/java/cotw/server/domain/payment/repository/PaymentRepository.java
  src/main/java/cotw/server/domain/payment/service/PaymentService.java
  src/main/resources/application.yml
  src/test/java/cotw/server/domain/payment/PaymentDataIntegrityTest.java
  src/test/java/cotw/server/domain/payment/PaymentIntegrationTest.java
  src/test/java/cotw/server/domain/payment/config/TestConfig.java
  src/test/java/cotw/server/domain/payment/controller/PaymentControllerTest.java
  src/test/java/cotw/server/domain/payment/controller/SecurityTestConfig.java
  src/test/java/cotw/server/domain/payment/service/LedgerServiceTest.java
  src/test/java/cotw/server/domain/payment/service/PaymentServiceTest.java
Labels: refactor

#27 Feat/mypage
  src/main/java/cotw/server/common/BaseEntity.java
  src/main/java/cotw/server/common/RetentionCleanupJob.java
  src/main/java/cotw/server/common/auth/CustomOAuth2UserService.java
  src/main/java/cotw/server/common/auth/OAuth2LoginSuccessHandler.java
  src/main/java/cotw/server/common/config/SchedulingConfig.java
  src/main/java/cotw/server/common/jwt/JwtFilter.java
  src/main/java/cotw/server/common/jwt/JwtUtil.java
  src/main/java/cotw/server/common/jwt/LoginFilter.java
  src/main/java/cotw/server/common/jwt/repository/RefreshTokenRepository.java
  src/main/java/cotw/server/common/security/SecurityConfig.java
  src/main/java/cotw/server/domain/member/Dto/request/DeactivateRequestDTO.java
  src/main/java/cotw/server/domain/member/Dto/request/SignUpRequestDTO.java
  src/main/java/cotw/server/domain/member/Dto/response/ShowInfoResponseDTO.java
  src/main/java/cotw/server/domain/member/Dto/response/SignUpResponseDTO.java
  src/main/java/cotw/server/domain/member/controller/MemberController.java
  src/main/java/cotw/server/domain/member/controller/ReissueController.java
  src/main/java/cotw/server/domain/member/entity/AccountStatus.java
  src/main/java/cotw/server/domain/member/entity/Member.java
  src/main/java/cotw/server/domain/member/repository/MemberRepository.java
  src/main/java/cotw/server/domain/member/service/MemberService.java
Labels: feat

#30 feat: 게시글 생성·수정 시 이미지 처리 기능 추가
  build.gradle
  src/main/java/cotw/server/common/config/S3Config.java
  src/main/java/cotw/server/common/jwt/LoginFilter.java
  src/main/java/cotw/server/domain/board/controller/PostController.java
  src/main/java/cotw/server/domain/board/dto/request/PostCreateRequestDto.java
  src/main/java/cotw/server/domain/board/dto/request/PostUpdateRequestDto.java
  src/main/java/cotw/server/domain/board/entity/Post.java
  src/main/java/cotw/server/domain/board/service/PostService.java
Labels: feat

#31 Feat/mypage
  src/main/java/cotw/server/common/jwt/CustomUserDetails.java
  src/main/java/cotw/server/common/jwt/JwtUtil.java
  src/main/java/cotw/server/common/jwt/LoginFilter.java
  src/main/java/cotw/server/common/jwt/MemberStatusPostChecker.java
  src/main/java/cotw/server/common/security/SecurityConfig.java
  src/main/java/cotw/server/domain/member/Dto/request/PatchImageReqeustDTO.java
  src/main/java/cotw/server/domain/member/Dto/request/PatchPasswordRequestDTO.java
  src/main/java/cotw/server/domain/member/Dto/response/ShowInfoResponseDTO.java
  src/main/java/cotw/server/domain/member/controller/MemberController.java
  src/main/java/cotw/server/domain/member/service/MemberService.java
Labels: feat, fix

#29 Fix/comment report
  src/main/java/cotw/server/domain/board/entity/Comment.java
  src/main/java/cotw/server/domain/comment/controller/CommentAdminController.java
  src/main/java/cotw/server/domain/comment/controller/CommentReportController.java
  src/main/java/cotw/server/domain/comment/dto/request/ReportRequest.java
  src/main/java/cotw/server/domain/comment/dto/response/ReportResponse.java
  src/main/java/cotw/server/domain/comment/entity/CommentLike.java
  src/main/java/cotw/server/domain/comment/entity/CommentReport.java
  src/main/java/cotw/server/domain/comment/entity/ReportReason.java
  src/main/java/cotw/server/domain/comment/repository/CommentReportRepository.java
  src/main/java/cotw/server/domain/comment/service/CommentReportService.java
Labels: fix

#32 Feat/payment
  build.gradle
  src/main/java/cotw/server/domain/member/service/MemberService.java
  src/main/java/cotw/server/domain/payment/controller/PaymentController.java
  src/main/java/cotw/server/domain/payment/dto/response/PaymentDetailResponse.java
  src/main/java/cotw/server/domain/payment/dto/response/PaymentHistoryResponse.java
  src/main/java/cotw/server/domain/payment/entity/PaymentLedger.java
  src/main/java/cotw/server/domain/payment/entity/PaymentTransaction.java
  src/main/java/cotw/server/domain/payment/entity/TransactionResult.java
  src/main/java/cotw/server/domain/payment/entity/TransactionType.java
  src/main/java/cotw/server/domain/payment/repository/PaymentLedgerRepository.java
  src/main/java/cotw/server/domain/payment/repository/PaymentTransactionRepository.java
  src/main/java/cotw/server/domain/payment/service/LedgerService.java
  src/main/java/cotw/server/domain/payment/service/PaymentService.java
  src/main/java/cotw/server/domain/payment/service/TransactionService.java
  src/main/resources/application.yml
  src/test/java/cotw/server/domain/payment/controller/PaymentControllerTest.java
  src/test/java/cotw/server/domain/payment/service/PaymentServiceTest.java
Labels: feat, fix

#38 feat: 공지사항 이미지 업로드 및 게시글 공개 설정 기능 추가
  src/main/java/cotw/server/common/security/SecurityConfig.java
  src/main/java/cotw/server/domain/board/controller/NoticeController.java
  src/main/java/cotw/server/domain/board/controller/PostController.java
  src/main/java/cotw/server/domain/board/dto/request/NoticeRequestDto.java
  src/main/java/cotw/server/domain/board/dto/request/PostCreateRequestDto.java
  src/main/java/cotw/server/domain/board/dto/response/NoticeResponseDto.java
  src/main/java/cotw/server/domain/board/entity/Notice.java
  src/main/java/cotw/server/domain/board/service/NoticeService.java
  src/main/java/cotw/server/domain/board/service/PostService.java
Labels: feat

#39 feat: Refresh token을 redis에 저장하여 운용하는 기능 구현, 마이페이지 기부내역 간단히 보기 관련 로직 …
  .gitignore
  build.gradle
  docker-compose.yml
  src/main/java/cotw/server/common/RetentionCleanupJob.java
  src/main/java/cotw/server/common/auth/OAuth2LoginSuccessHandler.java
  src/main/java/cotw/server/common/config/RedisConfig.java
  src/main/java/cotw/server/common/jwt/CustomLogoutFilter.java
  src/main/java/cotw/server/common/jwt/JwtUtil.java
  src/main/java/cotw/server/common/jwt/LoginFilter.java
  src/main/java/cotw/server/common/jwt/MemberStatusPostChecker.java
  src/main/java/cotw/server/common/jwt/controller/ReissueController.java
  src/main/java/cotw/server/common/jwt/entity/RefreshToken.java
  src/main/java/cotw/server/common/jwt/repository/RefreshTokenJpaRepository.java
  src/main/java/cotw/server/common/jwt/repository/RefreshTokenRepository.java
  src/main/java/cotw/server/common/jwt/service/DualStoreRefreshTokenService.java
  src/main/java/cotw/server/common/jwt/service/JpaRefreshTokenStore.java
  src/main/java/cotw/server/common/jwt/service/RedisRefreshTokenStore.java
  src/main/java/cotw/server/common/jwt/service/RefreshTokenService.java
  src/main/java/cotw/server/common/security/SecurityConfig.java
  src/main/java/cotw/server/domain/member/Dto/request/PatchNicknameRequestDTO.java
  src/main/java/cotw/server/domain/member/Dto/request/SignUpRequestDTO.java
  src/main/java/cotw/server/domain/member/controller/MemberController.java
  src/main/java/cotw/server/domain/member/entity/Member.java
  src/main/java/cotw/server/domain/member/service/MemberService.java
  src/main/java/cotw/server/domain/payment/repository/PaymentOrderRepository.java
Labels: feat, fix

#41 Feat/mypage
  src/main/java/cotw/server/common/jwt/JwtFilter.java
  src/main/java/cotw/server/common/security/SecurityConfig.java
  src/main/java/cotw/server/domain/member/Dto/response/ShowInfoResponseDTO.java
  src/main/java/cotw/server/domain/member/service/MemberService.java
  src/main/java/cotw/server/domain/payment/repository/PaymentOrderRepository.java
Labels: fix

#40 Feat/admin comment
  src/main/java/cotw/server/common/jwt/LoginFilter.java
  src/main/java/cotw/server/domain/admin/controller/AdminDashboardController.java
  src/main/java/cotw/server/domain/admin/controller/AdminPostController.java
  src/main/java/cotw/server/domain/admin/controller/AdminReportController.java
  src/main/java/cotw/server/domain/admin/controller/AdminStatsController.java
  src/main/java/cotw/server/domain/admin/dto/request/AdminPostStatusUpdateRequest.java
  src/main/java/cotw/server/domain/admin/dto/request/AdminReportBulkActionRequest.java
  src/main/java/cotw/server/domain/admin/dto/response/AdminDashboardSummaryResponse.java
  src/main/java/cotw/server/domain/admin/dto/response/AdminDonationStatsResponse.java
  src/main/java/cotw/server/domain/admin/dto/response/AdminPostDetailResponse.java
  src/main/java/cotw/server/domain/admin/dto/response/AdminPostSummaryResponse.java
  src/main/java/cotw/server/domain/admin/dto/response/AdminReportDetailResponse.java
  src/main/java/cotw/server/domain/admin/dto/response/AdminReportItemResponse.java
  src/main/java/cotw/server/domain/admin/dto/response/AdminTopDonorResponse.java
  src/main/java/cotw/server/domain/admin/service/AdminPostService.java
  src/main/java/cotw/server/domain/admin/service/AdminReportService.java
  src/main/java/cotw/server/domain/admin/service/AdminStatsService.java
  src/main/java/cotw/server/domain/comment/repository/CommentReportRepository.java
  src/main/java/cotw/server/domain/comment/repository/CommentRepository.java
  src/main/java/cotw/server/domain/member/service/MemberService.java
  src/main/java/cotw/server/domain/payment/repository/PaymentOrderRepository.java
Labels: feat
